apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: monitoring
  namespace: redhat-ods-monitoring
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: monitoring
    name: monitoring
  repos:
  - name: manifests
    uri: https://github.com/maroroman/odh-manifests
    ref: j4617
  version: v1.0.0
